### ISSUE TITLE
What MIB

### ISSUE THREAD

**Issue by astateofmind01** [besmartbeopen/dashboard-grafana-prometheus-arista#1]
Hello,

not quite an issue but can you detail which MIB is used? Thanks.

**Comment by besmartdeveloper** [comment]
Hi @astateofmind1,
the telemetry isn't exported through SNMP using a specific MIB but it is pushed to Prometheus using https://github.com/aristanetworks/goarista/blob/master/cmd/ocprometheus/README.md. The telemetry data is exported by ocprometheus using the Prometheus metrics format.

Kind regards
Be Smart Be Open dev team
