### ISSUE TITLE
unable to import json file

### ISSUE THREAD

**Issue by mhprabin** [besmartbeopen/dashboard-grafana-prometheus-arista#2]
<img width="777" alt="arista_grafana" src="https://user-images.githubusercontent.com/52509978/103483397-0ac47a80-4db5-11eb-9042-93272c96c4d9.png">

I tried to import json file but it's giving me error message "Unexpected error"

**Comment by besmartdeveloper** [comment]
Which Grafana version are you using? I've just tried to import it on our grafana v7.3.4 and it works nicely.
Did you import it using the url https://grafana.com/grafana/dashboards/10222?

**Comment by mhprabin** [comment]
i'm using grafana 7.3.6 and yes i import using this URL.

**Comment by besmartdeveloper** [comment]
I've just tried also with a new fresh grafana 7.3.6 and 7.3.7 and the dashboard is imported correctly.
Probably it's something specific to your grafana setup. 
I suggest you to try with a fresh grafana installation and check the differences with your current setup.
